BASE <https://w3id.org/hacid/data/cs/wf/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX top: <https://w3id.org/hacid/onto/top-level/>
PREFIX methods: <https://w3id.org/hacid/data/cs/wf/methods/>

SELECT 
	?method ?method_label
WHERE {
  	?general_method top:specializes methods:ClimateCaseMethod;
		rdfs:label ?general_method_label.
 	?method top:specializes ?general_method;
        rdfs:label ?specific_method_label.
 	BIND(CONCAT(?general_method_label, ' - ', ?specific_method_label) AS ?method_label)
}
ORDER BY ?method_label