BASE <https://w3id.org/hacid/data/cs/wf/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX top: <https://w3id.org/hacid/onto/top-level/>
PREFIX method_role: <app-profile/roles/Method>
PREFIX ops: <ops/>

SELECT 
	?label ?method
WHERE {
    {
  	    ?op top:isRealizedByMethod ?method
    } UNION {
        ?op top:isSpecializedBy ?method.
        FILTER(?op != ops:FilterClimateProjections)
    } UNION {
 	    ?op top:isRealizedByPlan/top:definesTask/top:executedThroughOperation ?method
        FILTER NOT EXISTS {?other_op1 top:isRealizedByMethod|top:isSpecializedBy ?method}
        FILTER NOT EXISTS {?method top:isRealizedByMethod|top:isSpecializedBy|(top:isRealizedByPlan/top:definesTask/top:executedThroughOperation) ?other_op2}
        FILTER (?op != ops:ClimateProjectionSelection)
        FILTER (?op != ops:ClimateServiceCaseResolution)
    }
  	?op rdfs:label ?op_label.
	?method rdfs:label ?method_label.
  	BIND(CONCAT(?op_label, ' - ', ?method_label) AS ?label)
}
ORDER BY ?label
