PREFIX ccso: <https://w3id.org/hacid/onto/ccso/>
PREFIX data: <https://w3id.org/hacid/onto/data/>
PREFIX dimension: <https://w3id.org/hacid/data/cs/dimension/>

# Get geodetic (spatial) resolutions for simulations

SELECT DISTINCT ?simulation ?geodeticDiscretization ?geodeticResolution
WHERE {
    ?simulation a ccso:ClimateSimulation;
        ccso:hasOutput/data:dependsOnVariable ?geodeticVariable.
    ?geodeticVariable
        data:holdsSpecializationOfVariable* dimension:geodetic;
        data:hasDiscretization ?geodeticDiscretization.
    OPTIONAL {?geodeticDiscretization data:hasResolutionValue ?geodeticResolution}
}
LIMIT 100