BASE <https://w3id.org/hacid/data/cs/wf/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX top: <https://w3id.org/hacid/onto/top-level/>
PREFIX wf: <https://w3id.org/hacid/data/cs/wf/>
PREFIX data_sel_task: <plans/ClimateInformationStudyPlan/tasks/ClimateInformationPreparation/subtasks/DataSelection>

# Get tasks

SELECT 
	?task ?task_label ?sub_task ?sub_task_label ?output_role
	(COUNT(DISTINCT ?following_task) AS ?num_following_tasks)
	(COUNT(DISTINCT ?following_sub_task) AS ?num_following_sub_tasks)
WHERE {
    {
        <plans/ClimateInformationStudyPlan> top:definesTask ?task.
	    ?task rdfs:label ?task_label.
        ?task top:hasPart ?sub_task.
        FILTER (?sub_task != data_sel_task:)
    } UNION {
        VALUES (?task ?task_label) {
            (data_sel_task: "Climate information preparation - Data selection"@en)
        }
        <plans/DatasetSelectionPlan> top:definesTask ?sub_task.
    }
    ?task top:directlyPrecedes* ?following_task.
    ?sub_task rdfs:label ?sub_task_label.
    ?sub_task top:directlyPrecedes* ?following_sub_task.
    OPTIONAL {
    	?sub_task top:sendsDefaultOutputToPlanRole ?output_role.
    }
    
}
GROUP BY ?task ?task_label ?sub_task ?sub_task_label ?output_role
ORDER BY DESC(?num_following_tasks) DESC(?num_following_sub_tasks)
