PREFIX ccso: <https://w3id.org/hacid/onto/ccso/>
PREFIX data: <https://w3id.org/hacid/onto/data/>
PREFIX dimension: <https://w3id.org/hacid/data/cs/dimensions/>

# Get temporal coverage for simulations

SELECT *
WHERE {
    ?simulation a ccso:ClimateSimulation;
        ccso:hasOutput/data:isSpecializedAccordingTo [
            data:isSpecializationOn/data:holdsSpecializationOfVariable* dimension:time;
            data:hasSelectedRegion ?timeInterval
        ]
}
LIMIT 100