PREFIX ccso: <https://w3id.org/hacid/onto/ccso/>
PREFIX data: <https://w3id.org/hacid/onto/data/>
PREFIX dimension: <https://w3id.org/hacid/data/cs/dimensions/>

# Get 1st level variables (MIP) used in simulations

SELECT ?var (COUNT(DISTINCT ?simulation) AS ?count)
WHERE {
    ?simulation a ccso:ClimateSimulation;
        ccso:hasOutput/data:holdsSpecializationOfVariable ?var
}
GROUP BY ?var
ORDER BY DESC(?count)
LIMIT 100