# Data ingestion workflow for the climate services KG.
#
# Run from the repository root, e.g.:
#   snakemake --cores 1                 # everything
#   snakemake --cores 1 cmor_tables     # just the CMOR tables
#   snakemake --cores 1 cmor_tables_analysis  # analysis of the CMOR tables editions

configfile: "config/config.yaml"


# Git repositories, through snakemake-storage-plugin-git (patched to support a
# git ref as URL fragment, e.g. https://github.com/PCMDI/cmip6-cmor-tables.git#6.9.33)
storage git:
    provider="git",
    keep_local=True,


include: "patches/git_storage_plugin.py"


include: "rules/cmor_tables.smk"


rule all:
    default_target: True
    input:
        rules.cmor_tables.input,
        rules.cmor_tables_analysis.output,
