# Data ingestion workflow for the climate services KG.
#
# Run from the repository root, e.g.:
#   snakemake --cores 1                 # everything
#   snakemake --cores 1 cmor_tables     # just the CMOR tables

configfile: "config/config.yaml"


# Git repositories, through snakemake-storage-plugin-git: each edition of the
# CMOR tables is cloned from https://{edition}@github.com/PCMDI/{source}-cmor-tables.git
# (GitHub ignores the user of public repositories) and its tag checked out
storage git:
    provider="git",
    keep_local=True,
    custom_heads={
        "https://{1}@github.com/PCMDI/{0}-cmor-tables.git".format(*edition.split("/")): {
            "tag": edition.split("/")[1]
        }
        for edition in config["cmor_tables"]["editions"]
    },


include: "lib/git_storage_fixes.py"


include: "rules/cmor_tables.smk"


rule all:
    default_target: True
    input:
        rules.cmor_tables.input,
