# Configuration of the data ingestion workflow (see workflow/Snakefile)

cmor_tables:
  # Editions of the CMOR tables to ingest, as {source}/{edition}, where
  # PCMDI/{source}-cmor-tables is the GitHub repository and {edition} one of
  # its git tags
  editions:
    - cmip5/5.0
    - cmip6/6.0.11
    - cmip6/6.0.12
    - cmip6/6.0.13
    - cmip6/6.0.14
    - cmip6/6.0.15
    - cmip6/6.0.16
    - cmip6/6.0.17
    - cmip6/6.0.18
    - cmip6/6.0.19
    - cmip6/6.0.19a
    - cmip6/6.0.20
    - cmip6/6.0.21
    - cmip6/6.1.22
    - cmip6/6.1.23
    - cmip6/6.2.24
    - cmip6/6.3.27
    - cmip6/6.3.27-fixed
    - cmip6/6.4.28
    - cmip6/6.5.29
    - cmip6/6.6.30
    - cmip6/6.7.31
    - cmip6/6.8.31
    - cmip6/6.9.32
    - cmip6/6.9.33
    - mip/v6.5.0.0
    - mip/v6.5.0.1
    - mip/v6.5.0.2
    - mip/v6.5.0.3
    - mip/v6.5.0.4
